
# Dataset and dataloadeers configuration
data:
  parameters:
    img_size : 224
    train_batch_size : 100
    valid_batch_size : 100
    test_batch_size : 100
    num_workers: 0
    pin_memory: True
  sampling:
    n_fold : 15
    valid_downsample : True
    downsample_quantity : 5000
    Random_sampling : True
    Rnd_sampling_q : 5000

# Model configuration for training and prediction
model:
  # Training model architecture and weights
  architecture:
    model_class : HCD_Model_ViT
    model_name : vit_small_r26_s32_224.augreg_in21k_ft_in1k
    load_model : False
    model_to_load : ''
    kwargs : {}

  # Training model parameters
  parameters:
    freeze_params : False
    epochs : 30
    es_count : 5
    es_reset : 10
    min_eta : 1.0e-3
    min_lr : 1.0e-6
    learning_rate : 1.0e-4
    weight_decay : 1.0e-5
    scheduler : CosineAnnealing
    retrain_from_auroc :
    save_checkpoints : True
    save_history : True
    history_name : 'history.json'

  # Training swa configuration
  swa:
    SWA_enable : False
    SWA_lr : 1.0e-4
    SWA_start : 0

  # Training cross validation configuration
  cross_val:
    cv_folds : 4
    retrain_cv : False

  # Prediction settings
  predictions:
    model_class: HCD_Model_ViT
    model_name: vit_small_r26_s32_224.augreg_in21k_ft_in1k
    file: 'SWA_Final_weights_epochs_20.bin'
    swa: True
    cv_folds: 1
    tta: True
    submission_name : 'tta_swa_vit_small_r26_s32_01.csv'

  # Ensemble settings
  ensemble:
    weighted_avg : False
    weights : 
    submission_name : SWA_4xTTA_ConvNextS_EffNet_SeResNet50_SwinS3T_ViTS.csv

# Miscellaneous
misc:
  seed : 42
  device : cuda