
# Configuraci칩n de los datasets y dataloaders
data:
  parameters:
    img_size : 224
    train_batch_size : 100
    valid_batch_size : 100
    test_batch_size : 100
    num_workers: 0
    pin_memory: True
  sampling:
    n_fold : 15
    valid_downsample : True
    downsample_quantity : 5000
    Random_sampling : True
    Rnd_sampling_q : 5000

# Configuraci칩n del modelo para entrenamiento y predicci칩n
model:
  architecture:
    model_class : HCD_Model_EffNet
    model_name : efficientnet_b0.ra4_e3600_r224_in1k
    load_model : True
    model_to_load : 'AUROC0.9820_Loss0.1747_epoch18.bin'
    kwargs : {}

  parameters:
    freeze_params : False
    epochs : 20
    es_count : 20
    es_reset : 5
    min_eta : 1.0e-3
    min_lr : 1.0e-4
    learning_rate : 1.0e-4
    weight_decay : 1.0e-5
    scheduler : 
    SWA_enable : True
    SWA_lr : 1.0e-4
    SWA_start : 0
    retrain_from_auroc :
    retrain_cv : False
    save_checkpoints : True
    save_history : True

  predictions:
    model_class: HCD_Model_EffNet
    model_name: efficientnet_b0.ra4_e3600_r224_in1k
    file: 'SWA_Final_weights_epochs_20.bin'
    swa: True
    cv_folds: 5
    tta: True
    submission_name : '4xTTA_ConvNextS_SWA_EffNet_SeResNet50_ViTS_SwinT.csv'

# Miscel치nea
misc:
  seed : 42
  device : cuda