
# Configuración de los datasets y dataloaders
data:
  parameters:
    img_size : 224
    train_batch_size : 100
    valid_batch_size : 100
    test_batch_size : 100
  sampling:
    n_fold : 15
    downsample : False
    downsample_quantity : 5000
    Random_sampling : True
    Rnd_sampling_q : 5000

# Configuración del modelo
model:
  architecture:
    model_class : HCD_Model_EffNet
    model_name : efficientnet_b0.ra4_e3600_r224_in1k
    checkpoint_path : 
    load_model : True
    model_to_load : 'AUROC0.9139_Loss0.3891_epoch22.bin'
    kwargs : {}

  parameters:
    freeze_params : False
    epochs : 50
    es_count : 10
    es_reset : 4
    min_eta : 1.0e-3
    min_lr : 1.0e-6
    learning_rate : 1.0e-4
    weight_decay : 1.0e-4
    scheduler : CosineAnnealingLR
    retrain_from_auroc : 0.9140

  mode:
    train_model : True
    save_checkpoints : True
  tta:
    file: 'AUROC0.9971_Loss0.0900_epoch35.bin'

# Miscelánea
misc:
  seed : 42
  save_submission : True
  submission_name : efficientnet_b0_submission_01.csv
  save_history : True
  device : cuda